version: "3.8"
services:
  # Mysql database container
  db:
    build: ./db
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - laravel-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Europe/Sofia
    networks:
      - laravel

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - laravel

networks:
  laravel:

volumes:
  laravel-db-data:
